package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"manav402/graphql/controller"
	"manav402/graphql/graph/model"
)

// CreateBook is the resolver for the CreateBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, createBook model.CreateBook) (*model.Book, error) {
	var inputData = model.Book{
		ID:    createBook.ID,
		Name:  createBook.Name,
		Price: createBook.Price,
	}
	outputdata, err := controller.CreateBook(inputData)
	return &outputdata, err
}

// GetBook is the resolver for the getBook field.
func (r *queryResolver) GetBook(ctx context.Context, bookID int) (*model.Book, error) {
	
	data, err := controller.GetBook(bookID)
	return &data,err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
